server:
#  port: 8088
  servlet:
    context-path: /demo02
spring:
  redis:
    host: 192.168.188.129
    port: 6379
  #在主配置文件中，通过该参数指定激活哪一个环境的配置文件 （-xxx）
  profiles:
    active: prod
java0824:
  stuname1: tom
  stuname2: tim
  stuname3: jerry
com:
  offcn:
    year: 20
    address: 五方桥
    code: 10098
dubbo:
  application:
    name: xxxaaabbb
  registry:
    address: zookeeper://192.168.188.129:2181
  protocol:
    port: 20882